
name: __SITE_NAME__
description: __DESCRIPTION__
url: __URL__
basedomain: __BASEDOMAIN__

# Color scheme based on http://flatuicolors.com/.
# Possible values:
# - default
# - dark
# - turquoise
# - green
# - blue
# - purple
# - orange
# - red
color: red

baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
paginate: 10
paginate_path: "page:num"

collections:
  my_tags:
    output: true
    permalink: /tag/:name/
  my_categories:
    output: true
    permalink: /category/:name/
  my_date:
    output: true
    permalink: /archives/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag
  -
    scope:
      path: ""
      type: my_date
    values:
      layout: archive
